import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function List() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ paddingLeft: '34%', paddingTop: '2%', display: 'flex' }}>
          <h2 style={{ paddingRight: '10px' }}>
            <Link href="/">Home</Link>
          </h2>
          <h2>
            <Link href="/list">List</Link>
          </h2>
        </div>
        <div style={{ paddingLeft: '34%', paddingTop: '3%' }}>
          <Image
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <Image
            src="/Spring_Logo.svg"
            alt="Spring Logo"
            width={200}
            height={45}
            priority
          />
        </div>
      </main>
    </>
  )
}