import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8"/>
        <title>Grumio&apos;'s List</title>
      </head>
      <body className={inter.className}>
      <title>Grumio&apos;'s List</title>
      <a href="/" className="m-2">Home</a>
      <a href="login.html" className="m-2">Login</a>
	    <a href="create.html" className="m-2">Create</a>
      <a href="profile.html" className="m-2">Profile</a>
      {children}
      </body>
      
    </html>
  );
}
