import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8"/>
        <title>Grumio&apos;'s List</title>
      </head>
      <body className={inter.className}>
      <title>Grumio&apos;'s List</title>
      <a href="/">Home</a>
      <a href="/login.html">Login</a>
        {children}
        </body>
      
    </html>
  );
}
